AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: adobe-app

Globals:
  Function:
    Timeout: 300

Parameters:
  WEATHER_API_URL:
    Type: String
    Description: Weather API URL
  WEATHER_API_APP:
    Type: String
    Description: Weather API APP ID
  WEATHER_API_KEY:
    Type: String
    Description: Weather API APP KEY

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.index.handler
      Runtime: python3.9
      Environment:
        Variables:
          WEATHER_API_URL: !Ref WEATHER_API_URL
          WEATHER_API_APP: !Ref WEATHER_API_APP
          WEATHER_API_KEY: !Ref WEATHER_API_KEY
      Architectures:
        - x86_64
      Events:
        default:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        weather:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /weather
            Method: get
